// <auto-generated />
using API_MUSIC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_MUSIC.Migrations.Artist
{
    [DbContext(typeof(ArtistContext))]
    [Migration("20230727003030_Upando")]
    partial class Upando
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_MUSIC.Controllers.Models.Artist", b =>
                {
                    b.Property<int>("IdArtist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StyleMusic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Yearofbirth")
                        .HasColumnType("int");

                    b.HasKey("IdArtist");

                    b.ToTable("artist");
                });
#pragma warning restore 612, 618
        }
    }
}
